### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by teairraxnicole** [GSRHackZ/EdgyBot_Edgenuity_Bot#132] opened 2023-03-30 03:16 UTC
I apologize if any of the issues im having have already been addressed etc. My bot wont let me choose what assignments i want it to do it just glitches out or goes to the next assignment thats due. and when I do finally get it to work the afk doesnt work I have to manually do it.

**Comment by ITAC85v2** [comment] 2023-03-30 12:46
This isn't an issue; this is how it worked in the past before we added back legacy EdgyAFK. You first need to pick a lesson to do, then click "Start EdgyBot" and it will only then start doing work AFK.

**Comment by teairraxnicole** [comment] 2023-03-30 21:00
right but it doesnt give me an option for it to pick anything for the bot to do. it just glitches out. I can send you a video if youd like but ive been using the bot for months now and it just started doing this.

**Comment by ITAC85v2** [comment] 2023-03-30 21:51
> right but it doesnt give me an option for it to pick anything for the bot to do. it just glitches out. I can send you a video if youd like but ive been using the bot for months now and it just started doing this.

Yes, could you please provide a video?

**Comment by GSRHackZ** [comment] 2023-03-30 22:50
The menu has been removed due to it being patched. The bot has been reverted to it's original form, before the legacy EdgyAFK menu was added to it again (after the first patch). So what exactly is the issue? And why did you phrase the title for this issue, "Multiple issues"?

**Comment by teairraxnicole** [comment] 2023-03-31 01:40
I titled it multiple issues because i stated 2 issues. Im sorry if im not being clear, i am trying to explain to the best of my ability. the last statment you said has basically answered my concerns. if there is no more menu all together that that solves that. I just am cinfused as to why when the bot is turned on im doing it manually. I can provide a video heresoon. I apologize for the inconvience.

**Comment by GSRHackZ** [comment] 2023-03-31 02:08
No worries, a video will really help 🙏

**Comment by teairraxnicole** [comment] 2023-03-31 03:01
Its not allowing me to attach the video. 
will the menu come back? or will this be a perm thing? 

You can close this, I will make due. Thank you!

**Comment by GSRHackZ** [comment] 2023-03-31 03:12
Menu will most likely be gone completely. Try a full reinstall of the script and see if that fixes it. If the issue hasn't been fixed in a week (if other people have the same bug they might report here and provide some more details or we might be able to identify a pattern between the issues and identify the cause of it) please reopen the issue.

**Closed by GSRHackZ** 2023-03-31 03:12 UTC
