### ISSUE TITLE
edgybot issue

### ISSUE THREAD

**Issue by bigbloodcb** [GSRHackZ/EdgyBot_Edgenuity_Bot#74] opened 2023-03-19 20:22 UTC
when the auto answer is taking a test it puts it as true or false when the questions are multiple choice?

**Comment by GSRHackZ** [comment] 2023-03-19 20:25
can you please send a picture of the issue here

**Comment by bigbloodcb** [comment] 2023-03-19 20:29
> can you please send a picture of the issue here

/
![Capture](https://user-images.githubusercontent.com/128324224/226207140-4ab7f5e7-7d0b-4b41-82db-389ccfeddf3b.PNG)

**Comment by bigbloodcb** [comment] 2023-03-19 20:55
i used this product before and it was fine but now it does that every time

**Comment by bigbloodcb** [comment] 2023-03-19 20:55
![Capture](https://user-images.githubusercontent.com/128324224/226208415-2bc59a57-2ef6-4fd8-9125-b28fe74a7fa7.PNG)

**Comment by ITAC85v2** [comment] 2023-03-20 13:08
I need to see what question \#1 is to determine the issue. Could you provide a screenshot of it?

**Comment by Coolkid6145** [comment] 2023-03-20 13:18
Why is it only answering true and false?

**Comment by 999LLJW** [comment] 2023-03-20 13:55
> I need to see what question #1 is to determine the issue. Could you provide a screenshot of it?

doesn't matter the question thats what it's doing

**Comment by ITAC85v2** [comment] 2023-03-20 13:57
> > I need to see what question #1 is to determine the issue. Could you provide a screenshot of it?
> 
> doesn't matter the question thats what it's doing

It does matter, I can't fix the issue if I don't know what the question and the answer choices are

**Comment by 999LLJW** [comment] 2023-03-20 13:58
> > > I need to see what question #1 is to determine the issue. Could you provide a screenshot of it?
> > 
> > 
> > doesn't matter the question thats what it's doing
> 
> It does matter, I can't fix the issue if I don't know what the question and the answer choices are

its doing it on everything tho even different classes

**Comment by 999LLJW** [comment] 2023-03-20 14:06
> I need to see what question #1 is to determine the issue. Could you provide a screenshot of it?
![Screenshot (4)](https://user-images.githubusercontent.com/44493415/226364786-716e28cd-01c3-43ab-8f34-17d38a2aac07.png)

**Comment by ITAC85v2** [comment] 2023-03-20 14:27
> > I need to see what question #1 is to determine the issue. Could you provide a screenshot of it?
>
> ![Screenshot (4)](https://user-images.githubusercontent.com/44493415/226364786-716e28cd-01c3-43ab-8f34-17d38a2aac07.png)

I can't see the question or answer choices in your screenshot, please take another.

**Comment by 999LLJW** [comment] 2023-03-20 14:44
> Thank you, looking into the issue now

It wasn't doing any of this before the update the 3.21v was working but was just failing test and quiz

**Comment by 999LLJW** [comment] 2023-03-20 15:58
> Thank you, looking into the issue now

how long does it usually take

**Comment by 999LLJW** [comment] 2023-03-20 16:02
> > > Thank you, looking into the issue now
> > 
> > 
> > how long does it usually take
> 
> It depends, for this issue it will take longer as I cannot seem to find the cause.

I say go back to the old one until this one gets fixed

**Comment by billyonedge** [comment] 2023-03-20 21:14
yes, is there any way to go back to the old version until it’s fixed? i have the same issue and i need to get my classes done in the mean time.

**Comment by GSRHackZ** [comment] 2023-03-20 22:16
Fix will be released later today. When the new version is released please report any issues it has here as well. We will keep this thread open until we fix all bugs (important ones).

**Comment by ITAC85v2** [comment] 2023-03-21 14:54
Update to v3.23 and tell me if the issue is resolved.

**Comment by GSRHackZ** [comment] 2023-03-21 17:23
Update to v2.34 and this issue would be fixed, it uses a new method to get answers and has issue & error handling. has been tested by 16 new uesers and they aren't having issues anymore. This issue is resolved, if it continues (it won't but if you have any issues related to the new one) make a new issue.

**Closed by GSRHackZ** 2023-03-21 17:23 UTC
Labels: bug, ongoing
