### ISSUE TITLE
Edgybot

### ISSUE THREAD

**Issue by Khiairi** [GSRHackZ/EdgyBot_Edgenuity_Bot#50] opened 2023-02-27 05:49 UTC
It doesn't let me choose the class I want it to work on and it automatically opens a class and starts working no matter what I do it wont stop

**Comment by ITAC85v2** [comment] 2023-02-27 13:25
This is a known issue, we're working on a fix. Please be patient 🙏

**Comment by catandmosue** [comment] 2023-02-27 13:34
hello how are you got the bot having trouble getting it

**Comment by Khiairi** [comment] 2023-02-27 20:03
When is the bug going to be fixed ?

**Comment by ITAC85v2** [comment] 2023-02-27 22:24
At most a week, but probably less. In the meantime, try updating to the latest version if you haven't already.

**Comment by GSRHackZ** [comment] 2023-02-27 23:56
> hello how are you got the bot having trouble getting it

Please follow the instructions here: https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/blob/main/instructions.md

**Comment by GSRHackZ** [comment] 2023-02-27 23:57
> It doesn't let me choose the class I want it to work on and it automatically opens a class and starts working no matter what I do it wont stop

Uninstall Tampermonkey and reinstall then follow steps here: https://github.com/GSRHackZ/EdgyBot_Edgenuity_Bot/blob/main/instructions.md

You will now have v3.0.5 or up, which should fix the issue

**Comment by ITAC85v2** [comment] 2023-02-28 03:02
The issue is now fixed. Please update to the latest version.

**Closed by ITAC85v2** 2023-02-28 03:02 UTC
Labels: bug, good first issue

**Comment by catandmosue** [comment] 2023-02-28 13:43
still not working i only need this for one class

**Comment by catandmosue** [comment] 2023-02-28 23:19
is edgy bot free this week im trying to get it nothing

**Comment by ITAC85v2** [comment] 2023-02-28 23:24
Yes.

**Comment by catandmosue** [comment] 2023-02-28 23:27
i need this bot for one class thats all how do i do this

**Comment by ITAC85v2** [comment] 2023-02-28 23:28
[Activate it here](https://edgybot-gsrhackz.web.app/)

**Comment by catandmosue** [comment] 2023-02-28 23:33
thank you so much got it
